#!/bin/bash

echo Setting up variables

USER=deploy
DOCUMENT_ROOT=/var/www/nominatim
PLANET=http://download.geofabrik.de/europe/andorra-latest.osm.bz2
RAM=5102
THREADS=$(nproc)

# install dependencies
echo Updating repositories
apt-get update
apt-get dist-upgrade -y
echo Installing dependencies
apt-get install -y build-essential libxml2-dev libgeos-dev libpq-dev libbz2-dev libtool automake libproj-dev libboost-dev libboost-system-dev libboost-filesystem-dev libboost-thread-dev gcc proj-bin libgeos-c1 osmosis libgeos++-dev php5 php-pear php5-pgsql php5-json php-db postgresql postgis postgresql-contrib postgresql-9.3-postgis-2.1 postgresql-server-dev-9.3 libprotobuf-c0-dev protobuf-c-compiler git autoconf-archive nginx php5-fpm git fail2ban htop libxml-parser-perl

echo Adding a user
useradd -m -s /bin/bash $USER

echo Adding a postgres user

# setup db
sudo -u postgres createuser -s $USER
sudo -u postgres createuser -SDR www-data

echo Coping postgres config file
cat conf/postgresql.conf > /etc/postgresql/9.3/main/postgresql.conf

echo Restarting postgres
service postgresql restart

# setup web server
echo Coping nginx config file
cat conf/nginx.conf > /etc/nginx/sites-available/default
echo Configuring and creating document root for nginx
mkdir -p -m 755 $DOCUMENT_ROOT
chown $USER:$USER $DOCUMENT_ROOT
echo Restarting nginx
service nginx restart

# install osmosis
echo Downloading osmosis binaries
cd /opt
mkdir osmosis
wget http://bretth.dev.openstreetmap.org/osmosis-build/osmosis-latest.zip
unzip osmosis-latest.zip -d osmosis
rm osmosis-latest.zip

# compile
echo Making Nominatim install directory
sudo -u $USER mkdir /home/${USER}/nominatim

echo Changing directories
cd /home/${USER}/nominatim

echo Cloning nominatim
sudo -u $USER git clone --recursive git://github.com/twain47/Nominatim.git .
echo Getting ready to build
sudo -u $USER ./autogen.sh
sudo -u $USER ./configure
echo Making nominatim
sudo -u $USER make

# download planet
sudo -u $USER wget $PLANET -P data

# download optional data
sudo -u $USER wget --output-document=data/wikipedia_article.sql.bin http://www.nominatim.org/data/wikipedia_article.sql.bin
sudo -u $USER wget --output-document=data/wikipedia_redirect.sql.bin http://www.nominatim.org/data/wikipedia_redirect.sql.bin
sudo -u $USER wget --output-document=data/gb_postcode_data.sql.gz http://www.nominatim.org/data/gb_postcode_data.sql.gz

# load data
sudo -u $USER ./utils/setup.php --osm-file data/planet-latest.osm.bz2 --all --osm2pgsql-cache $RAM --threads $THREADS

sudo -u $USER ./utils/specialphrases.php --countries > data/specialphrases_countries.sql
sudo -u $USER psql -d nominatim -f data/specialphrases_countries.sql

sudo -u $USER ./utils/specialphrases.php --wiki-import > data/specialphrases.sql
sudo -u $USER psql -d nominatim -f data/specialphrases.sql

# cleanup
sudo -u $USER rm data/*

# enable hierarchical updates
sudo -u $USER ./utils/setup.php --create-functions --enable-diff-updates

echo "GRANT usage ON SCHEMA public TO \"www-data\";" \
     "GRANT SELECT ON ALL TABLES IN SCHEMA public TO \"www-data\";" | psql -d nominatim

# create web
sudo -u $USER ./utils/setup.php --create-website $DOCUMENT_ROOT

